spikes_configs:
  GRRCP_no_robust:
    laps_params:
      lambda_1: 0
      lambda_2: 0
      lambda_smooth: 2900 
      lambda_interval: 8300
      measure: "dot"
      ks_1: 0
      ks_2: 0
  GRRTucker_no_robust:
    laps_params:
      lambda_1: 0
      lambda_2: 0
      lambda_smooth: 111
      lambda_interval: 24
      measure: "dot"
      ks_1: 0
      ks_2: 0

events_configs:
  GRRTucker_no_robust:
    laps_params:
      lambda_1: 0
      lambda_2: 0
      lambda_smooth: 150
      lambda_interval: 49 
      measure: "dot"
      ks_1: 0
      ks_2: 0
  GRRCP_no_robust:
    laps_params:
      lambda_1: 0
      lambda_2: 0
      lambda_smooth: 5259
      lambda_interval: 126
      measure: "dot"
      ks_1: 0
      ks_2: 0


ddos_configs:
  GRRCP_no_robust:
    laps_params:
      lambda_1: 0
      lambda_2: 0
      lambda_smooth: 9318
      lambda_interval: 998 
      measure: "dot"
      ks_1: 0
      ks_2: 0
  GRRTucker_no_robust:
    laps_params:
      lambda_1: 0
      lambda_2: 0
      lambda_smooth: 208
      lambda_interval: 100
      measure: "dot"
      ks_1: 0
      ks_2: 0

outage_configs:
  GRRCP_no_robust:
    laps_params:
      lambda_1: 0
      lambda_2: 0
      lambda_smooth: 
      lambda_interval:  
      measure: "dot"
      ks_1: 0
      ks_2: 0
  GRRTucker_no_robust:
    laps_params:
      lambda_1: 0
      lambda_2: 0
      lambda_smooth: 
      lambda_interval: 
      measure: "dot"
      ks_1: 0
      ks_2: 0


