spikes_configs:
  GRRCP_no_robust:
    laps_params:
      lambda_1: 0
      lambda_2: 0
      lambda_smooth: 100
      lambda_interval: 0 
      measure: "dot"
      ks_1: 0
      ks_2: 0
  GRRTucker_no_robust:
    laps_params:
      lambda_1: 0
      lambda_2: 0
      lambda_smooth: 10
      lambda_interval: 0
      measure: "dot"
      ks_1: 0
      ks_2: 0

events_configs:
  GRRCP_no_robust:
    laps_params:
      lambda_1: 0
      lambda_2: 0
      lambda_smooth: 10
      lambda_interval: 200
      measure: "dot"
      ks_1: 0
      ks_2: 0
  GRRTucker_no_robust:
    laps_params:
      lambda_1: 0
      lambda_2: 0
      lambda_smooth: 1
      lambda_interval: 10
      measure: "dot"
      ks_1: 0
      ks_2: 0


ddos_configs:
  GRRCP_no_robust:
    laps_params:
      lambda_1: 0
      lambda_2: 0
      lambda_smooth: 4000
      lambda_interval: 4000 
      measure: "dot"
      ks_1: 0
      ks_2: 0
  GRRTucker_no_robust:
    laps_params:
      lambda_1: 0
      lambda_2: 0
      lambda_smooth: 208
      lambda_interval: 100
      measure: "dot"
      ks_1: 0
      ks_2: 0

outage_configs:
  GRRCP_no_robust:
    laps_params:
      lambda_1: 0
      lambda_2: 0
      lambda_smooth: 
      lambda_interval:  
      measure: "dot"
      ks_1: 0
      ks_2: 0
  GRRTucker_no_robust:
    laps_params:
      lambda_1: 0
      lambda_2: 0
      lambda_smooth: 
      lambda_interval: 
      measure: "dot"
      ks_1: 0
      ks_2: 0


